### ISSUE TITLE
Calendar selection on Call To Meet

### ISSUE THREAD

**Issue by maiksd** [iflorit/iflorit.github.io#1]
Hi Ismael,

I'm the one who wrote the App Store review about the calendars, thanks for your response. I guess it's better to discuss that here? Let me try to explain the issue in more detail.

I have a number of calendars configured to be visible on the watch, and the calendar app on it reflects that. Only a few of my calendars are checked, most are deactivated.

What Call to Meet does is show me all items from all existing calendars, even those who are marked invisible in calendar settings. One of those happens to have a lot of items that I rarely need to check, and those are flooding the entire view of events in the watch app, so I can't even find the real items of the enabled calendar items containing my meetings, because it will only load a certain number of items overall.

Maik

**Comment by iflorit** [comment]
Hello Maik :)

I appreciate your detailed issue 👍 

So I will try to find a way to keep invisible the items marked as invisible ASAP.

Again thanks for your feedback and even more to use this little app!

**Comment by iflorit** [comment]
Hello Maik, 

I've found a way to hide all-day events or events without call number. In few days I will also to add options to choose the visible calendars.

I appreciate your comments and will help a lot to change your App Store valorisation if the app fits better to your necessities.

Thanks a lot!
